---
version: "2.1"
services:
  backup:
    image: ghcr.io/johannmx/paperless-ngx_backup:main
    container_name: paperless-ngx_backup
    volumes:
      - /docker/paperless/data:/data:ro # Read-only
      - /backups/paperless/:/backups
      #- /etc/localtime:/etc/localtime:ro # Container uses date from host.
    environment:
      - DELETE_AFTER=30
      #- CRON_TIME=*/5 * * * * # At every 5th minute.
      - CRON_TIME=0 3 * * * # Runs at 3am.
      - UID=1000
      - GID=100
      - TZ=America/Argentina/Buenos_Aires # Specify a timezone to use EG Europe/London.
      - WATCHTOWER_LABEL_ENABLE=false
      - GOTIFY_TOKEN=supertoken
      - GOTIFY_SERVER=subdomain.domain.com
      - SLACK_WEBHOOK=slakwebhook
      - DISCORD_WEBHOOK_ID=discordwebhookid
      - DISCORD_WEBHOOK_TOKEN discordwebhooktoken