services:
  backup:
    image: ghcr.io/johannmx/paperless-ngx_backup:main
    container_name: paperless-ngx_backup
    restart: unless-stopped
    volumes:
      - /path/to/paperless/data:/data:ro
      - /path/to/backups:/backups
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CRON_TIME=0 3 * * *
      - DELETE_AFTER=30
      - COMPRESSION=zstd
      - UID=1000
      - GID=1000
      - TZ=America/Argentina/Buenos_Aires
      # Example Apprise URLs:
      # - gotifys://server/token
      # - discord://webhookid/webhooktoken
      # - mailto://user:pass@domain.com
      - APPRISE_URLS=
